### ISSUE TITLE
Post-processor Tab overhaul

### ISSUE THREAD

**Issue by cdbell01** [quantum-dan/DeCal#30]
Feel like this could use a major cosmetic / workflow overhaul.  Open to ideas?  Minimally, this tab could use more instruction:
1 - define and explain values in the table; give tips on how they should be used during calibration process
2 - Explain purpose of toggling through results

**Comment by quantum-dan** [comment]
Explanations added, since I don't have any particular ideas for cosmetic overhauls.  The scatterplot can be fixed, but it will be a rather involved process necessitating curve fitting etc, since the probabilities on the two CDFs don't match up exactly and hence can't be used to pair the corresponding values--I think that it is probably better to leave that for now, or just remove it.
